apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoria-metrics
    type: prometheus
    # host network で同居しているため localhost 経由
    url: http://127.0.0.1:8428
    isDefault: true
    access: proxy
    editable: false
    jsonData:
      timeInterval: "15s"
